name: {{name.snakeCase()}}
description: A sample appwrite function
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: "2.17.7"

dev_dependencies:
  lints: ^2.0.0
# dependencies:
#   appwrite: ^8.1.0
